### PR TITLE
login page styling

### PR DESCRIPTION
**Pull request by loustevenshere**
I changed the LoginContainer.js file to customize the styling and text for the Boys and Girls Club. 
I also added the boys and girls club logo to the component.

### CODE REVIEW

**Review by PhatherJean — APPROVED** [review]
Everything looks good self explanatory Great Job lets keep up the good work

**Comment by PhatherJean** [comment]
As it stand it is all good from what I can see and looks good

**Review by Ironipad64 — APPROVED** [review]
Looks good to me, it should be good to go now

**Comment by kayode94** [comment]
I can see it as well, looks great

**Review by kayode94 — COMMENTED** [review]
Very nice and clean

**Pull request merged**
