### PR TITLE
Feature/pass id thru

### PR DESCRIPTION
**Pull request by PhatherJean**

### CODE REVIEW

**Comment by PhatherJean** [comment]
I have complete the passing of the student id that is scanned or typed in so that through out the whole process the YDP and student will know which user who information is being recorded. It is passed through fwd and bkwd so if a selection is e YDP and student will know which user who information
made accidently it student can go back and not have to start all over from the scan.

**Review by roberttierie — CHANGES_REQUESTED** [review]
Super job Pat!! Great job figuring this out. There is an issue in that there are two versions of the success page? I see the older one I made last week (pages/SuccessPage/Success.js ) which I discarded and the recent one I pushed ( src/components/pages/Success/Success.js) yesterday.

**Comment by PhatherJean** [comment]
> Super job Pat!! Great job figuring this out. There is an issue in that there are two versions of the success page? I see the older one I made last week (pages/SuccessPage/Success.js ) which I discarded and the recent one I pushed ( src/components/pages/Success/Success.js) yesterday.

I just sent it to both so either or it is still will work

**Review by roberttierie — APPROVED** [review]

**Review by loustevenshere — COMMENTED** [review]
Looks good to me, I am curious how that history.push works with the studentId attached to it, that is interesting. Also do we not need the QRCODEGENERATOR in the index.js anymore?

**Comment by PhatherJean** [comment]
The conflict error is taken care of and merged to main

**Pull request closed without merging**
